# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - run: npm ci
    - run: npm test
      env:
        TEST_FIREBASE_API_KEY: ${{ secrets.TEST_FIREBASE_API_KEY }}
        TEST_FIREBASE_AUTH_DOMAIN: ${{ secrets.TEST_FIREBASE_AUTH_DOMAIN }}
        TEST_FIREBASE_DATABASE_URL: ${{ secrets.TEST_FIREBASE_DATABASE_URL }}
        TEST_FIREBASE_PROJECT_ID: ${{ secrets.TEST_FIREBASE_PROJECT_ID }}
        TEST_FIREBASE_STORAGE_BUCKET: ${{ secrets.TEST_FIREBASE_STORAGE_BUCKET }}
        TEST_FIREBASE_SENDER_ID: ${{ secrets.TEST_FIREBASE_SENDER_ID }}
        TEST_FIREBASE_APP_ID: ${{ secrets.TEST_FIREBASE_APP_ID }}
        
    
